### ISSUE TITLE
Output size is too small

### ISSUE THREAD

**Issue by csapot** [danoneata/xts#3]
after following the readme (install requirements, download data, etc), I tried to run a basic training:

```
python train.py --hparams magnus -d grid --filelist k-s01 -v
```

but there is an issue with that: 

```
Current run is terminating due to exception: Given input size: (512x2x2). Calculated output size: (512x-4x-4). Output size is too small.
Engine run is terminating due to exception: Given input size: (512x2x2). Calculated output size: (512x-4x-4). Output size is too small.
```

do you know why this happens?

**Comment by danoneata** [comment]
Hello! I believe your are using an older version of `torch-vision`: [in their previous implementation of ResNet the last layer was `AvgPool2d` but it was subsequently replaced with `AdaptiveAvgPool2d`](https://github.com/pytorch/vision/commit/dc0238b82f0df5c44ec9878cb41011d1852a7afd), which pools information across the entire image and, crucially, outputs a tensor of size D × 1 × 1 regardless of the size of the input image. I hope this helps!

**Comment by csapot** [comment]
yes, torchvision update solved it, now the training is running. thanks for the quick answer!Ű
maybe it would be worth adding this specific version to requirements.txt?
