### ISSUE TITLE
'ascii' codec can't encode character '\u2190' in position 31: ordinal not in range(128)

### ISSUE THREAD

**Issue by csapot** [danoneata/xts#4]
"←" character should be removed from https://github.com/danoneata/xts/blob/4acac1279397894d10fdff6ce123b0efc25937fe/train.py#L257

**Comment by danoneata** [comment]
Hello! Thank you very much for the report, but I'm having trouble replicating this error. If you run `locale` in the command line, what is its output? You may need to specify the UTF-8 encoding either by setting `LANG=en_US.UTF-8` or by setting `PYTHONIOENCODING=utf-8`. I assume you use Python 3, right?

**Comment by csapot** [comment]
true; I was using a non-UTF-8 locale.
